# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160929_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDetails',
            new_name='CarDetail',
        ),
    ]
