# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20160929_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='rating',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], decimal_places=1, max_digits=2),
        ),
    ]
